//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Stygitan.rc
//
#define IDR_CODE_PURIFIER               101
#define IDR_DEFAULT_EDITOR_CONFIG       102
#define IDR_EDITORCONFIG_APPLIER        103
#define IDR_FILTERED_COMMITS_MESSAGE_CREATOR 104
#define IDR_MAINFRAME                   105
#define IDD_CODE_PURIFIER               106
#define IDD_EDITORCONFIG_APPLIER        107
#define IDD_FILTERED_COMMITS_MESSAGE_CREATOR 108
#define IDD_PROPERTIES                  109
#define IDC_APPLY_EDITORCONFIG_RULES    1000
#define IDC_BRANCH_COPIES               1002
#define IDC_CLEAN_COMMIT                1003
#define IDC_COMMITS                     1004
#define IDC_CREATE_BRANCH_COPY          1005
#define IDC_CREATE_BRANCH_COPY_BEFORE_RESET 1006
#define IDC_CREATE_FILTERED_COMMIT_TEXT 1007
#define IDC_CREATE_LIST_OF_APPLICABLE_RULES 1008
#define IDC_CREATE_LIST_OF_GIT_IGNORED_FILES 1009
#define IDC_CREATE_TEMPORARY_COMMIT_ALL 1010
#define IDC_CREATE_TEMPORARY_COMMIT_STAGED 1011
#define IDC_DELETE_BRANCH_COPIES        1012
#define IDC_DESTINATION_BRANCH          1013
#define IDC_DESTINATION_REPO            1014
#define IDC_DIFF_TOOL_ARGUMENTS         1015
#define IDC_DIFF_TOOL_COMMAND           1016
#define IDC_DIFF_TOOL_SELECT            1017
#define IDC_DIFF_TOOL_TEST              1018
#define IDC_DIRECTORY                   1019
#define IDC_DIRECTORY_SELECT            1020
#define IDC_FILTERED_COMMIT             1021
#define IDC_FILTERED_REPO               1022
#define IDC_LOCAL_BRANCH                1023
#define IDC_LOG                         1024
#define IDC_MODIFIED_FILES              1025
#define IDC_PROCESS_ALL_FILES           1026
#define IDC_PROCESS_ONLY_FILES_IN_GIT_INDEX 1027
#define IDC_PROCESS_ONLY_MODIFIED_FILES_GIT 1028
#define IDC_REMOTE_BRANCH               1029
#define IDC_RESET_BRANCH_TO_CLEAN_COMMIT 1030
#define IDC_USE_CSPRO_DEFAULT_EDITORCONFIG 1031
#define IDC_WORKING_DIRECTORY           1032
#define ID_COMMITS_CREATE_MESSAGE_FROM_FILTERED_COMMITS 40001
#define ID_FILE_OPEN_CODE_PURIFIER      40002
#define ID_FILE_OPEN_EDITORCONFIG_APPLIER 40003
#define ID_MODIFIED_FILE_COPY_PATH      40004
#define ID_MODIFIED_FILE_DIFF           40005
#define ID_MODIFIED_FILE_OPEN           40006
#define ID_MODIFIED_FILE_OPEN_CONTAINING_FOLDER 40007
#define ID_PROPERTIES                   40008
#define ID_SET_CLEAN_COMMIT             40009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1033
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
