//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Stygitan.rc
//
#define IDR_CODE_PURIFIER               101
#define IDR_DEFAULT_EDITOR_CONFIG       102
#define IDR_EDITORCONFIG_APPLIER        103
#define IDR_FILTERED_COMMITS_MESSAGE_CREATOR 104
#define IDR_MAINFRAME                   105
#define IDR_MODIFIED_FILES_ACTIONS      106
#define IDD_CODE_PURIFIER               107
#define IDD_EDITORCONFIG_APPLIER        108
#define IDD_FILTERED_COMMITS_MESSAGE_CREATOR 109
#define IDD_PROPERTIES                  110
#define IDD_REMOVAL_CONFIRMATION        111
#define IDC_APPLY_EDITORCONFIG_RULES    1000
#define IDC_APPLY_EDITORCONFIG_RULES_BEFORE_RESET 1001
#define IDC_BRANCH_COPIES               1002
#define IDC_CLEAN_COMMIT                1003
#define IDC_COMMITS                     1004
#define IDC_CREATE_BRANCH_COPY          1005
#define IDC_CREATE_BRANCH_COPY_BEFORE_RESET 1006
#define IDC_CREATE_FILTERED_COMMIT_TEXT 1007
#define IDC_CREATE_LIST_OF_APPLICABLE_RULES 1008
#define IDC_CREATE_LIST_OF_GIT_IGNORED_FILES 1009
#define IDC_CREATE_TEMPORARY_COMMIT_ALL 1010
#define IDC_CREATE_TEMPORARY_COMMIT_STAGED 1011
#define IDC_DELETE                      1012
#define IDC_DELETE_BRANCH_COPIES        1013
#define IDC_DESTINATION_BRANCH          1014
#define IDC_DESTINATION_REPO            1015
#define IDC_DIFF_TOOL_ARGUMENTS         1016
#define IDC_DIFF_TOOL_COMMAND           1017
#define IDC_DIFF_TOOL_SELECT            1018
#define IDC_DIFF_TOOL_TEST              1019
#define IDC_DIRECTORY                   1020
#define IDC_DIRECTORY_SELECT            1021
#define IDC_FILTERED_COMMIT             1022
#define IDC_FILTERED_REPO               1023
#define IDC_LOCAL_BRANCH                1024
#define IDC_LOG                         1025
#define IDC_MODIFIED_FILES              1026
#define IDC_MODIFIED_FILES_BUTTON       1027
#define IDC_PATHS                       1028
#define IDC_PROCESS_ALL_FILES           1029
#define IDC_PROCESS_ONLY_FILES_IN_GIT_INDEX 1030
#define IDC_PROCESS_ONLY_MODIFIED_FILES_GIT 1031
#define IDC_RECYCLE                     1032
#define IDC_REMOTE_BRANCH               1033
#define IDC_RESET_BRANCH_TO_CLEAN_COMMIT 1034
#define IDC_USE_CSPRO_DEFAULT_EDITORCONFIG 1035
#define IDC_WORKING_DIRECTORY           1036
#define ID_COMMITS_CREATE_MESSAGE_FROM_FILTERED_COMMITS 40001
#define ID_FILE_OPEN_CODE_PURIFIER      40002
#define ID_FILE_OPEN_EDITORCONFIG_APPLIER 40003
#define ID_MODIFIED_FILE_COPY_PATH      40004
#define ID_MODIFIED_FILE_DIFF           40005
#define ID_MODIFIED_FILE_OPEN           40006
#define ID_MODIFIED_FILE_OPEN_CONTAINING_FOLDER 40007
#define ID_PROPERTIES                   40008
#define ID_REMOVE_EMPTY_DIRECTORIES     40009
#define ID_REMOVE_UNTRACKED_FILES       40010
#define ID_SET_CLEAN_COMMIT             40011
#define ID_STAGE_TRACKED_FILES          40012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         40013
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
