<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Stygitan</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Stygitan.ico</ApplicationIcon>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <BaseOutputPath>$(SolutionDir)build\$(PlatformTarget)\$(Configuration)\</BaseOutputPath>
    <OutputPath>$(BaseOutputPath)bin</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Stygitan.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.30.0" />
  </ItemGroup>

</Project>