#include "stdafx.h"
#include "CSWebRepositoryCache.h"
#include "CSWebRepositoryCacheCredential.h"
#include "CSWebRepositoryJsonKeys.h"
#include "SyncBinaryDataUploadManager.h"
#include <zSql/Commands.h>
#include <zToolsO/FileIO.h>
#include <zUtilO/CredentialStore.h>
#include <zUtilO/Interapp.h>
#include <zNetwork/CSWebConnection.h>


namespace
{
    constexpr bool EncryptCache          = !DebugMode();
    constexpr const char* CacheExtension = EncryptCache ? "dbe" : "db";

    constexpr std::string_view CredentialAttribute_sv = "CSPro_csweb_cache";
    constexpr size_t CredentialHashLength             = 8; // used as 16 hex characters

    constexpr size_t CachePasswordHashLength = 128;
}


CSWebRepositoryCache::CSWebRepositoryCache(CSWebRepository& repository, const CSWebRepositoryCacheCredential& credential,
                                           const JsonNode& dictionary_metadata_json_node)
    :   m_repository(repository)
{
    constexpr int open_flags = Sqlite::OpenFlags::ReadWrite | Sqlite::OpenFlags::Create;

    if( credential.cache_password.has_value() )
    {
        m_db.OpenEncrypted(credential.cache_file_path, *credential.cache_password, open_flags);
    }

    else
    {
        m_db.Open(credential.cache_file_path, open_flags);
    }

    Initialize(dictionary_metadata_json_node);
}


CSWebRepositoryCache::~CSWebRepositoryCache()
{
}


std::unique_ptr<CSWebRepositoryCache> CSWebRepositoryCache::Create(CSWebRepository& repository, const DeviceId& server_device_id,
                                                                   const CSWebUser& user, const JsonNode& dictionary_metadata_json_node)
{
    const std::string& dictionary_name = repository.m_syncableDictionaryName;

    // see if there already is a cache created for this user
    CredentialStore credential_store;
    std::vector<CSWebRepositoryCacheCredential> credentials;

    try
    {
        const JsonNode json_node = credential_store.RetrieveFromJson<JsonNode>(CredentialAttribute_sv);
        credentials = json_node.GetArray().GetVector<CSWebRepositoryCacheCredential>();

        const auto& lookup = std::find_if(credentials.crbegin(), credentials.crend(),
            [&](const CSWebRepositoryCacheCredential& credential)
            {
                return ( server_device_id == credential.server_device_id &&
                         user == credential.user &&
                         dictionary_name == credential.dictionary_name &&
                         EncryptCache == credential.cache_password.has_value() );
            });

        if( lookup != credentials.crend() )
            return std::unique_ptr<CSWebRepositoryCache>(new CSWebRepositoryCache(repository, *lookup, dictionary_metadata_json_node));
    }

    catch(...)
    {
        // errors are ignored in favor of creating a new cache
        ASSERT(credential_store.Retrieve(CredentialAttribute_sv).empty());
    }

    // if here, we will create a new cache file in %AppData%/CSPro/csweb_cache/[dictionary_name]/
    ASSERT(dictionary_name == Path::CreateValidFilename(dictionary_name));

    const std::string cache_directory = Path::Combine(GetAppDataPath(), "csweb_cache", dictionary_name);
    std::string cache_file_path = PortableFunctions::GetUniqueFilePathInDirectory(cache_directory, CacheExtension);
    FileIO::CreateDirectoriesForFile(cache_file_path);

    // when used, the file password will be randomly generated by hashing some values together and using
    // the dictionary name as a salt;
    // CRYPT_TODO: if added to CSPro at some point, modify this to use a key derivation scheme
    std::optional<std::vector<std::byte>> cache_password;

    if constexpr(EncryptCache)
    {
        const std::string values_for_password_hash = SO::Concatenate(user.id, user.role_name, DoubleToString(GetTimestamp()));

        cache_password.emplace(Hash::Hash(
            reinterpret_cast<const std::byte*>(values_for_password_hash.data()),
            values_for_password_hash.length(),
            reinterpret_cast<const std::byte*>(dictionary_name.data()),
            dictionary_name.length(),
            CachePasswordHashLength
        ));
    }

    CSWebRepositoryCacheCredential credential
    {
        server_device_id,
        user,
        dictionary_name,
        std::move(cache_file_path),
        std::move(cache_password)
    };

    auto cache = std::unique_ptr<CSWebRepositoryCache>(new CSWebRepositoryCache(repository, credential, dictionary_metadata_json_node));

    // on success, store the new credential
    credentials.emplace_back(std::move(credential));
    credential_store.StoreAsJson(CredentialAttribute_sv, credentials);

    return cache;
}


void CSWebRepositoryCache::Initialize(const JsonNode& dictionary_metadata_json_node)
{
    ASSERT(m_repository.m_caseAccess != nullptr);
    ASSERT(!m_currentServerRevision.has_value());

    // get details on the server's current max revision
    m_currentServerRevision = dictionary_metadata_json_node.GetOptional<int64_t>(JK::maxRevision);

    // clear old queries...
    if( m_db.TableExists("queries") )
    {
        ClearOldQueries();
    }

    // ...or create the cache tables and indices
    else
    {
        CreateTablesAndIndices();
    }

    // speed up access to the database by disabling journaling and synchronous writes
    m_db.Execute(Sqlite::Commands::SetJournalModeToOff);
    m_db.Execute(Sqlite::Commands::SetSynchronousOff);
}


void CSWebRepositoryCache::CreateTablesAndIndices()
{
    // `queries`
    m_db.Execute(
        "CREATE TABLE `queries` ("
        "`arguments` TEXT NOT NULL,"
        "`server_revision` INTEGER NOT NULL,"
        "`json` INTEGER NOT NULL,"
        "PRIMARY KEY(`arguments`)"
        ");"
    );

    // `single_case_positions`
    m_db.Execute(
        "CREATE TABLE `single_case_positions` ("
        "`arguments` TEXT NOT NULL,"
        "`server_revision` INTEGER NOT NULL,"
        "`position` INTEGER NOT NULL,"
        "PRIMARY KEY(`arguments`)"
        ");"
    );

    // `cases`
    m_db.Execute(
        "CREATE TABLE `cases` ("
        "`position` INTEGER NOT NULL,"
        "`uuid` TEXT NOT NULL,"
        "`key` TEXT NOT NULL,"
        "`deleted` INTEGER NULL,"               // null when querying identifiers
        "`case_revision` INTEGER NOT NULL,"     // the case's revision (on CSWeb)
        "`server_revision` INTEGER NOT NULL,"   // CSWeb's revision when the row was written
        "`query_type` INTEGER NOT NULL,"        // the value of CSWebCaseQuery of the case cached
        "`json` TEXT NOT NULL,"
        "`metadata_json` TEXT,"                 // non-null when querying cases
        "PRIMARY KEY(`position`)"
        ");"
    );

    // `cases_key_index`: index on `cases`.`key`
    m_db.Execute(
        "CREATE INDEX `cases_key_index` "
        "ON `cases` (`key`)"
    );

    // `binary_data`
    m_db.Execute(
        "CREATE TABLE `binary_data` ("
        "`signature` TEXT NOT NULL,"
        "`data` BLOB NOT NULL,"
        "PRIMARY KEY(`signature`)"
        ");"
    );
}


void CSWebRepositoryCache::ClearOldQueries()
{
    for( const char* const table_name : { "queries", "single_case_positions" } )
    {
        const std::string sql = FormatText("DELETE FROM `%s` WHERE `server_revision` < " Formatter_int64_t ";",
                                           table_name,
                                           m_currentServerRevision.value_or(std::numeric_limits<int64_t>::max()));
        m_db.Execute(sql);
    }
}


void CSWebRepositoryCache::DeleteCache(std::unique_ptr<CSWebRepositoryCache>& cache) noexcept
{
    if( cache == nullptr )
        return;

    try
    {
        const std::string cache_file_path = cache->m_db.GetFilePath();
        cache.reset();
        PortableFunctions::FileDeleteWithExceptions(cache_file_path);
    }
    catch(...) { ASSERT(false); }
}


bool CSWebRepositoryCache::IsServerRevisionKnown() noexcept
{
    if( m_currentServerRevision.has_value() )
        return true;

    // try to get the latest server revision
    try
    {
        const JsonNode dictionary_metadata_json_node = m_repository.m_cswebConnection->GetDictionaryMetadata(m_repository.m_syncableDictionaryName);
        m_currentServerRevision = dictionary_metadata_json_node.GetOptional<int64_t>(JK::maxRevision);
    }
    catch(...) { ASSERT(false); }

    return m_currentServerRevision.has_value();
}


void CSWebRepositoryCache::CacheQuery(const std::string_view arguments_json_text_sv, const JsonNode& count_json_node) noexcept
{
    if( !IsServerRevisionKnown() )
        return;

    try
    {
        m_db.PrepareOrResetStatement(m_stmtWriteQuery,
            "INSERT OR REPLACE INTO `queries` "
            "(`arguments`, `server_revision`, `json`) "
            "VALUES(?,?,?);"
        );

        m_stmtWriteQuery.Bind(1, arguments_json_text_sv)
                        .Bind(2, *m_currentServerRevision)
                        .Bind(3, count_json_node.GetNodeAsString());

        if( m_stmtWriteQuery.Step() != Sqlite::Result::Done )
            throw ProgrammingErrorException();
    }
    catch(...) { ASSERT(false); }
}


std::optional<JsonNode> CSWebRepositoryCache::RetrieveQuery(const std::string_view arguments_json_text_sv) noexcept
{
    if( !IsServerRevisionKnown() )
        return std::nullopt;

    try
    {
        m_db.PrepareOrResetStatement(m_stmtReadQuery,
            "SELECT `json` "
            "FROM `queries` "
            "WHERE `arguments` = ? AND `server_revision` >= ?;"
        );

        m_stmtReadQuery.Bind(1, arguments_json_text_sv)
                       .Bind(2, *m_currentServerRevision);

        const int result = m_stmtReadQuery.Step();

        if( result == Sqlite::Result::Row )
            return Json::Parse(m_stmtReadQuery.GetColumn<std::string>(0));

        ASSERT(result == Sqlite::Result::Done);
    }
    catch(...) { ASSERT(false); }

    return std::nullopt;
}


template<CSWebCaseQuery query>
const JsonNode& CSWebRepositoryCache::GetContentJsonNode(const CSWebCaseResponse<query>& response)
{
    if constexpr(query == CSWebCaseQuery::cases)
    {
        return response.response.case_json_node;
    }

    else
    {
        return response.response;
    }
}


template<CSWebCaseQuery query>
const JsonNode& CSWebRepositoryCache::GetMetadataJsonNode(const CSWebCaseResponse<query>& response)
{
    if constexpr(query == CSWebCaseQuery::cases)
    {
        return response.response.metadata_json_node;
    }

    else
    {
        return response.response;
    }
}


template<CSWebCaseQuery query>
void CSWebRepositoryCache::CacheCase(const CSWebCaseResponse<query>& response) noexcept
{
    if( !IsServerRevisionKnown() )
        return;

    try
    {
        const JsonNode& metadata_json_node = GetMetadataJsonNode(response);
        const int64_t position = metadata_json_node.Get<int64_t>(JK::position);
        const int64_t case_revision = metadata_json_node.Get<int64_t>(JK::revision);

        // do not update the case cache if it already exists with the same or more details
        m_db.PrepareOrResetStatement(m_stmtReadCaseExistenceByQueryType,
            "SELECT 1 "
            "FROM `cases` "
            "WHERE `position` = ? AND `case_revision` >= ? AND `query_type` >= ?;"
        );

        m_stmtReadCaseExistenceByQueryType.Bind(1, position)
                                          .Bind(2, case_revision)
                                          .Bind(3, static_cast<int>(query));

        if( m_stmtReadCaseExistenceByQueryType.Step() == Sqlite::Result::Row )
            return;

        // update the case cache
        m_db.PrepareOrResetStatement(m_stmtWriteCase,
            "INSERT OR REPLACE INTO `cases` "
            "(`position`, `uuid`, `key`, `deleted`, `case_revision`, `server_revision`, `query_type`, `json`, `metadata_json`) "
            "VALUES(?,?,?,?,?,?,?,?,?);"
        );

        const JsonNode& content_json_node = GetContentJsonNode(response);

        m_stmtWriteCase.Bind(1, position)
                       .Bind(2, content_json_node.Get<std::string>(JK::uuid))
                       .Bind(3, content_json_node.Get<std::string>(JK::key));

        if constexpr(query == CSWebCaseQuery::identifiers)
        {
            m_stmtWriteCase.BindNull(4);
        }

        else
        {
            m_stmtWriteCase.Bind(4, content_json_node.GetOrDefault(JK::deleted, false));
        }

        m_stmtWriteCase.Bind(5, case_revision)
                       .Bind(6, *m_currentServerRevision)
                       .Bind(7, static_cast<int>(query))
                       .Bind(8, content_json_node.GetNodeAsString());

        if constexpr(query != CSWebCaseQuery::cases)
        {
            m_stmtWriteCase.BindNull(9);
        }

        else
        {
            m_stmtWriteCase.Bind(9, response.response.metadata_json_node.GetNodeAsString());
        }

        if( m_stmtWriteCase.Step() != Sqlite::Result::Done )
            throw ProgrammingErrorException();
   }
    catch(...) { ASSERT(false); }
}


template<CSWebCaseQuery query, int position_column_number, int json_column_number, int metadata_column_number>
CSWebCaseResponse<query> CSWebRepositoryCache::CreateCaseResponseFromQuery(Sqlite::Statement& stmt)
{
    if constexpr(query == CSWebCaseQuery::cases)
    {
        ASSERT(!stmt.IsColumnNull(metadata_column_number));

        return { Json::Parse(stmt.GetColumn<std::string>(json_column_number)),
                 Json::Parse(stmt.GetColumn<std::string>(metadata_column_number)) };
    }

    else
    {
        std::string content_json_text = stmt.GetColumn<std::string>(json_column_number);

        // if a full case is stored but identifiers or summaries are requested, add the position
        // into the JSON (because the full case JSON does not have the positino)
        if( !stmt.IsColumnNull(metadata_column_number) )
        {
            SO::MakeTrimRight(content_json_text);
            ASSERT(!content_json_text.empty() && content_json_text.back() == '}');

            content_json_text.replace(content_json_text.length() - 1, 1,
                                        FormatText(",\"position\":" Formatter_int64_t "}",
                                                    stmt.GetColumn<int64_t>(position_column_number)));
        }

        return { Json::Parse(content_json_text) };
    }
}


template<CSWebCaseQuery query>
CSWebCaseResponse<query> CSWebRepositoryCache::RetrieveCaseUnmodifiedOnServer(const int64_t position)
{
    if( !IsServerRevisionKnown() )
        throw ProgrammingErrorException();

    // update the server revision
    m_db.PrepareOrResetStatement(m_stmtUpdateCaseServerRevision,
        "UPDATE `cases` "
        "SET `server_revision` = ? "
        "WHERE `position` = ?;"
    );

    m_stmtUpdateCaseServerRevision.Bind(1, *m_currentServerRevision)
                                  .Bind(2, position);

    if( m_stmtUpdateCaseServerRevision.Step() != Sqlite::Result::Done )
        throw ProgrammingErrorException();

    // query the case
    m_db.PrepareOrResetStatement(m_stmtReadCase,
        "SELECT `position`, `json`, `metadata_json` "
        "FROM `cases` "
        "WHERE `position` = ?;"
    );

    m_stmtReadCase.Bind(1, position);

    if( m_stmtReadCase.Step() != Sqlite::Result::Row )
        throw ProgrammingErrorException();

    return CreateCaseResponseFromQuery<query, 0, 1, 2>(m_stmtReadCase);
}

template CSWebCaseResponse<CSWebCaseQuery::identifiers> CSWebRepositoryCache::RetrieveCaseUnmodifiedOnServer(int64_t position);
template CSWebCaseResponse<CSWebCaseQuery::cases> CSWebRepositoryCache::RetrieveCaseUnmodifiedOnServer(int64_t position);


template<CSWebCaseQuery query>
void CSWebRepositoryCache::CacheSingleCaseQuery(const std::string_view arguments_json_text_sv,
                                                const CSWebCaseResponse<query>& response) noexcept
{
    if( !IsServerRevisionKnown() )
        return;

    try
    {
        const int64_t position = GetMetadataJsonNode(response).template Get<int64_t>(JK::position);

        // update the arguments -> case position cache
        m_db.PrepareOrResetStatement(m_stmtWriteSingleCasePosition,
            "INSERT OR REPLACE INTO `single_case_positions` "
            "(`arguments`, `server_revision`, `position`) "
            "VALUES(?,?,?);"
        );

        m_stmtWriteSingleCasePosition.Bind(1, arguments_json_text_sv)
                                     .Bind(2, *m_currentServerRevision)
                                     .Bind(3, position);

        if( m_stmtWriteSingleCasePosition.Step() != Sqlite::Result::Done )
            throw ProgrammingErrorException();

        // update the case cache
        CacheCase(response);
    }
    catch(...) { ASSERT(false); }
}

template void CSWebRepositoryCache::CacheSingleCaseQuery(std::string_view arguments_json_text_sv, const CSWebCaseResponse<CSWebCaseQuery::identifiers>& response) noexcept;
template void CSWebRepositoryCache::CacheSingleCaseQuery(std::string_view arguments_json_text_sv, const CSWebCaseResponse<CSWebCaseQuery::cases>& response) noexcept;


template<CSWebCaseQuery query>
CSWebCacheCaseResponse<query> CSWebRepositoryCache::RetrieveSingleCaseQuery(const std::string_view arguments_json_text_sv) noexcept
{
    if( !IsServerRevisionKnown() )
        return { };

    try
    {
        m_db.PrepareOrResetStatement(m_stmtReadSingleCasePosition,
            "SELECT `cases`.`position`, `cases`.`server_revision`, `cases`.`json`, `cases`.`metadata_json` "
            "FROM `single_case_positions` "
            "JOIN `cases` ON `cases`.`position` = `single_case_positions`.`position` "
            "WHERE `single_case_positions`.`arguments` = ? AND "
                  "`single_case_positions`.`server_revision` >= ? AND "
                  "`cases`.`query_type` >= ?;"
        );

        m_stmtReadSingleCasePosition.Bind(1, arguments_json_text_sv)
                                    .Bind(2, *m_currentServerRevision)
                                    .Bind(3, static_cast<int>(query));

        if( m_stmtReadSingleCasePosition.Step() != Sqlite::Result::Row )
            return { };

        // if the cache contains the case but with an earlier server revision value,
        // indicate that we have the case but that CSWeb needs to be queried to see if
        // there is a newer case
        const int64_t server_revision = m_stmtReadSingleCasePosition.GetColumn<int64_t>(1);

        if( server_revision < *m_currentServerRevision )
        {
            using OldCaseDataT = typename CSWebCacheCaseResponse<query>::OldCaseData;
            return { OldCaseDataT { server_revision, m_stmtReadSingleCasePosition.GetColumn<int64_t>(0) } };
        }

        // otherwise, at this point, the case is up-to-date
        else
        {
            return { CreateCaseResponseFromQuery<query, 0, 2, 3>(m_stmtReadSingleCasePosition) };
        }
    }
    catch(...) { ASSERT(false); }

    return { };
}

template CSWebCacheCaseResponse<CSWebCaseQuery::identifiers> CSWebRepositoryCache::RetrieveSingleCaseQuery(std::string_view arguments_json_text_sv) noexcept;
template CSWebCacheCaseResponse<CSWebCaseQuery::cases> CSWebRepositoryCache::RetrieveSingleCaseQuery(std::string_view arguments_json_text_sv) noexcept;


bool CSWebRepositoryCache::HasNonDeletedCaseByKey(const std::string& key) noexcept
{
    if( !IsServerRevisionKnown() )
        return false;

    try
    {
        m_db.PrepareOrResetStatement(m_stmtReadCaseExistenceNotDeletedByKey,
            "SELECT 1 "
            "FROM `cases` "
            "WHERE `key` = ? AND `deleted` = 0 AND `server_revision` >= ? "
            "LIMIT 1;"
        );

        m_stmtReadCaseExistenceNotDeletedByKey.Bind(1, key)
                                              .Bind(2, *m_currentServerRevision);

        return ( m_stmtReadCaseExistenceNotDeletedByKey.Step() == Sqlite::Result::Row );
    }
    catch(...) { ASSERT(false); }

    return false;
}


void CSWebRepositoryCache::CacheBinaryData(const std::string& signature, const std::vector<std::byte>& content) noexcept
{
    // unlike the other methods, the server revision does not need to be checked
    // because binary data is stored using its MD5 so it is immutable

    try
    {
        m_db.PrepareOrResetStatement(m_stmtWriteBinaryData,
            "INSERT OR IGNORE INTO `binary_data` "
            "(`signature`, `data`) "
            "VALUES(?,?);"
        );

        m_stmtWriteBinaryData.Bind(1, signature)
                             .BindBlob(2, content);

        if( m_stmtWriteBinaryData.Step() != Sqlite::Result::Done )
            throw ProgrammingErrorException();
    }
    catch(...) { ASSERT(false); }
}


void CSWebRepositoryCache::CacheBinaryData(const SyncBinaryDataUploadManager& sync_binary_data_upload_manager) noexcept
{
    try
    {
        sync_binary_data_upload_manager.ForeachBinaryCaseItemInChunk(
            [&](const BinaryCaseItem& binary_case_item, const CaseItemIndex& index)
            {
                const BinaryDataAccessor& binary_data_accessor = binary_case_item.GetBinaryDataAccessor(index);
                const std::string& signature = binary_data_accessor.GetSignature();

                // check if the binary data has already been cached before actually loading the content
                if( !HasBinaryData(signature) )
                    CacheBinaryData(signature, binary_data_accessor.GetBinaryData().GetContent());
            });
    }
    catch(...) { ASSERT(false); }
}


bool CSWebRepositoryCache::HasBinaryData(const std::string& signature)
{
    m_db.PrepareOrResetStatement(m_stmtHasBinaryData,
        "SELECT 1 "
        "FROM `binary_data` "
        "WHERE `signature` = ?;"
    );

    m_stmtHasBinaryData.Bind(1, signature);

    const int result = m_stmtHasBinaryData.Step();
    ASSERT(result == Sqlite::Result::Row || result == Sqlite::Result::Done);

    return ( result == Sqlite::Result::Row );
}


std::optional<std::vector<std::byte>> CSWebRepositoryCache::RetrieveBinaryData(const std::string& signature) noexcept
{
    // unlike the other methods, the server revision does not need to be checked
    // because binary data is stored using its MD5 so it is immutable

    try
    {
        m_db.PrepareOrResetStatement(m_stmtReadBinaryData,
            "SELECT `data` "
            "FROM `binary_data` "
            "WHERE `signature` = ?;"
        );

        m_stmtReadBinaryData.Bind(1, signature);

        const int result = m_stmtReadBinaryData.Step();

        if( result == Sqlite::Result::Row )
            return m_stmtReadBinaryData.GetColumn<std::vector<std::byte>>(0);

        ASSERT(result == Sqlite::Result::Done);
    }
    catch(...) { ASSERT(false); }

    return std::nullopt;
}
