#include "stdafx.h"
#include "CSWebRepositoryCache.h"
#include "CSWebRepositoryCacheCredential.h"
#include "CSWebRepositoryJsonKeys.h"
#include <zToolsO/FileIO.h>
#include <zUtilO/CredentialStore.h>
#include <zUtilO/Interapp.h>


namespace
{
    constexpr bool EncryptCache          = !DebugMode();
    constexpr const char* CacheExtension = EncryptCache ? "dbe" : "db";

    constexpr std::string_view CredentialAttribute_sv = "CSPro_csweb_cache";
    constexpr size_t CredentialHashLength             = 8; // used as 16 hex characters

    constexpr size_t CachePasswordHashLength = 128;
}


CSWebRepositoryCache::CSWebRepositoryCache(CSWebRepository& repository, const CSWebRepositoryCacheCredential& credential,
                                           const JsonNode& dictionary_metadata_json_node)
    :   m_repository(repository)
{
    constexpr int open_flags = Sqlite::OpenFlags::ReadWrite | Sqlite::OpenFlags::Create;

    if( credential.cache_password.has_value() )
    {
        m_db.OpenEncrypted(credential.cache_file_path, *credential.cache_password, open_flags);
    }

    else
    {
        m_db.Open(credential.cache_file_path, open_flags);
    }

    Initialize(dictionary_metadata_json_node);
}


std::unique_ptr<CSWebRepositoryCache> CSWebRepositoryCache::Create(CSWebRepository& repository, const DeviceId& server_device_id,
                                                                   const CSWebUser& user, const JsonNode& dictionary_metadata_json_node)
{
    const std::string& dictionary_name = repository.m_syncableDictionaryName;

    // see if there already is a cache created for this user
    CredentialStore credential_store;
    std::vector<CSWebRepositoryCacheCredential> credentials;

    try
    {
        const JsonNode json_node = credential_store.RetrieveFromJson<JsonNode>(CredentialAttribute_sv);
        credentials = json_node.GetArray().GetVector<CSWebRepositoryCacheCredential>();

        const auto& lookup = std::find_if(credentials.crbegin(), credentials.crend(),
            [&](const CSWebRepositoryCacheCredential& credential)
            {
                return ( server_device_id == credential.server_device_id &&
                         user == credential.user &&
                         dictionary_name == credential.dictionary_name &&
                         EncryptCache == credential.cache_password.has_value() );
            });

        if( lookup != credentials.crend() )
            return std::unique_ptr<CSWebRepositoryCache>(new CSWebRepositoryCache(repository, *lookup, dictionary_metadata_json_node));
    }

    catch(...)
    {
        // errors are ignored in favor of creating a new cache
        ASSERT(credential_store.Retrieve(CredentialAttribute_sv).empty());
    }

    // if here, we will create a new cache file in %AppData%/CSPro/csweb_cache/[dictionary_name]/
    ASSERT(dictionary_name == Path::CreateValidFilename(dictionary_name));

    const std::string cache_directory = Path::Combine(GetAppDataPath(), "csweb_cache", dictionary_name);
    std::string cache_file_path = PortableFunctions::GetUniqueFilePathInDirectory(cache_directory, CacheExtension);
    FileIO::CreateDirectoriesForFile(cache_file_path);

    // when used, the file password will be randomly generated by hashing some values together and using
    // the dictionary name as a salt;
    // CRYPT_TODO: if added to CSPro at some point, modify this to use a key derivation scheme
    std::optional<std::vector<std::byte>> cache_password;

    if constexpr(EncryptCache)
    {
        const std::string values_for_password_hash = SO::Concatenate(user.id, user.role_name, DoubleToString(GetTimestamp()));

        cache_password.emplace(Hash::Hash(
            reinterpret_cast<const std::byte*>(values_for_password_hash.data()),
            values_for_password_hash.length(),
            reinterpret_cast<const std::byte*>(dictionary_name.data()),
            dictionary_name.length(),
            CachePasswordHashLength
        ));
    }

    CSWebRepositoryCacheCredential credential
    {
        server_device_id,
        user,
        dictionary_name,
        std::move(cache_file_path),
        std::move(cache_password)
    };

    auto cache = std::unique_ptr<CSWebRepositoryCache>(new CSWebRepositoryCache(repository, credential, dictionary_metadata_json_node));

    // on success, store the new credential
    credentials.emplace_back(std::move(credential));
    credential_store.StoreAsJson(CredentialAttribute_sv, credentials);

    return cache;
}


void CSWebRepositoryCache::Initialize(const JsonNode& dictionary_metadata_json_node)
{
    const std::optional<int64_t> min_revision = dictionary_metadata_json_node.GetOptional<int64_t>(JK::minRevision);
    const std::optional<int64_t> max_revision = dictionary_metadata_json_node.GetOptional<int64_t>(JK::maxRevision);

    // CSWEB_TODO: check versus cache;
    // if min_revision is std::nullopt or is > the cache's revision, it means that the data was deleted via the CSWeb UI, so the entire cache should be cleared
}
