#include "stdafx.h"
#include "CSWebRepositoryCache.h"
#include "CSWebRepositoryCacheCredential.h"
#include "CSWebRepositoryJsonKeys.h"
#include <zToolsO/FileIO.h>
#include <zUtilO/Interapp.h>


namespace
{
    constexpr bool EncryptCache          = !DebugMode();
    constexpr const char* CacheExtension = EncryptCache ? "dbe" : "db";

    constexpr size_t CredentialHashLength    = 8; // used as 16 hex characters
    constexpr size_t CachePasswordHashLength = 128;
}


// --------------------------------------------------------------------------
// CSWebRepositoryCacheCredentialStore
// --------------------------------------------------------------------------

CSWebRepositoryCacheCredentialStore::CSWebRepositoryCacheCredentialStore(const std::string& dictionary_name, const CSWebUser& user)
    :   m_prefix("CSPro_csweb_cache_")
{
    ASSERT(!dictionary_name.empty() && !user.id.empty() && !user.role_name.empty());

    // the credential will be stored using a hash of the concatenated user ID, role, and cache extension,
    // using the dictionary name as a salt;
    // adding the cache extension allows debug/release builds to use different credentials
    // that point to different cache files
    m_prefix.append(Hash::Hash(FormatText("%s-%s-%s", user.id.c_str(), user.role_name.c_str(), CacheExtension),
                               CredentialHashLength,
                               dictionary_name));
}


std::string CSWebRepositoryCacheCredentialStore::PrefixAttribute(const std::string& attribute)
{
    ASSERT(attribute.empty());
    return m_prefix;
}



// --------------------------------------------------------------------------
// CSWebRepositoryCache
// --------------------------------------------------------------------------

CSWebRepositoryCache::CSWebRepositoryCache(CSWebRepository& repository, const CSWebRepositoryCacheCredential& credential,
                                           const JsonNode& dictionary_metadata_json_node)
    :   m_repository(repository)
{
    constexpr int open_flags = Sqlite::OpenFlags::ReadWrite | Sqlite::OpenFlags::Create;

    if constexpr(EncryptCache)
    {
        m_db.OpenEncrypted(credential.cache_file_path, credential.cache_password, open_flags);
    }

    else
    {
        m_db.Open(credential.cache_file_path, open_flags);
    }

    Initialize(dictionary_metadata_json_node);
}


std::unique_ptr<CSWebRepositoryCache> CSWebRepositoryCache::Create(CSWebRepository& repository, const CSWebUser& user,
                                                                   const JsonNode& dictionary_metadata_json_node)
{
    // see if there already is a cache created for this user
    CSWebRepositoryCacheCredentialStore credential_store(repository.m_syncableDictionaryName, user);
    std::optional<CSWebRepositoryCacheCredential> credential = credential_store.RetrieveOptionalFromJson<CSWebRepositoryCacheCredential>("");

    if( credential.has_value() )
    {
        try
        {
            return std::unique_ptr<CSWebRepositoryCache>(new CSWebRepositoryCache(repository, *credential, dictionary_metadata_json_node));
        }

        catch(...)
        {
            // on error we will simply create a new cache
            ASSERT(false);
        }
    }

    // if here, we will create a new cache file in %AppData%/CSPro/csweb_cache/[dictionary_name]/
    ASSERT(repository.m_syncableDictionaryName == Path::CreateValidFilename(repository.m_syncableDictionaryName));

    const std::string cache_directory = Path::Combine(GetAppDataPath(), "csweb_cache", repository.m_syncableDictionaryName);
    std::string cache_file_path = PortableFunctions::GetUniqueFilePathInDirectory(cache_directory, CacheExtension);
    FileIO::CreateDirectoriesForFile(cache_file_path);

    // the file password will be randomly generated by hashing some values together and using
    // the dictionary name as a salt;
    // CRYPT_TODO: if added to CSPro at some point, modify this to use a key derivation scheme
    const std::string values_for_password_hash = SO::Concatenate(user.id, user.role_name, DoubleToString(GetTimestamp()));

    std::vector<std::byte> cache_password = Hash::Hash(
        reinterpret_cast<const std::byte*>(values_for_password_hash.data()),
        values_for_password_hash.length(),
        reinterpret_cast<const std::byte*>(repository.m_syncableDictionaryName.data()),
        repository.m_syncableDictionaryName.length(),
        CachePasswordHashLength
    );

    credential = CSWebRepositoryCacheCredential
    {
        repository.m_syncableDictionaryName,
        user,
        std::move(cache_file_path),
        std::move(cache_password)
    };

    auto cache = std::unique_ptr<CSWebRepositoryCache>(new CSWebRepositoryCache(repository, *credential, dictionary_metadata_json_node));

    // on success, store the credential
    credential_store.StoreAsJson("", *credential);

    return cache;
}


void CSWebRepositoryCache::Initialize(const JsonNode& dictionary_metadata_json_node)
{
    const std::optional<int64_t> min_revision = dictionary_metadata_json_node.GetOptional<int64_t>(JK::minRevision);
    const std::optional<int64_t> max_revision = dictionary_metadata_json_node.GetOptional<int64_t>(JK::maxRevision);

    // CSWEB_TODO: check versus cache;
    // if min_revision is std::nullopt or is > the cache's revision, it means that the data was deleted via the CSWeb UI, so the entire cache should be cleared
}
