//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CSPro.rc
//
#define IDR_APLTYPE                     101
#define IDR_MAINFRAME                   102
#define IDI_QSF_FILE                    103
#define IDI_XTS_FILE                    104
#define IDI_BCH_FILE                    105
#define IDI_XTB_FILE                    106
#define IDI_ICON_FILLER06               107
#define IDI_FILE_OPEN                   108
#define IDI_FILE_NEW                    109
#define IDI_DCF_FILE                    110
#define IDI_FRM_FILE                    111
#define IDI_ORD_FILE                    112
#define IDI_ENT_FILE                    113
#define IDI_MGF_FILE                    114
#define IDI_ENT_FILE_CAPI               115
#define IDI_ICON_FILLER01               116
#define IDI_ICON_FILLER02               117
#define IDI_ICON_FILLER03               118
#define IDI_ICON_FILLER04               119
#define IDI_ICON_FILLER05               120
#define IDI_ENC_FILE                    121
#define IDI_RESOURCE_FOLDER             122
#define IDI_CSDBE_FILE                  123
#define IDI_ENT_FILE_OPERATIONAL_CONTROL 124
#define IDI_ENT_FILE_ALL_TYPES          125
#define IDR_MEASURTYPE                  126
#define IDD_APLFILEASSOCIATIONSDLG      127
#define IDD_CAPI_MACROS                 128
#define IDD_COMMON_STORE                129
#define IDD_DIALOGBAR                   130
#define IDD_FONTPREFDLG                 131
#define IDD_NEW_ABOUT                   132
#define IDD_NEW_FILE                    133
#define IDD_ONKEY_CHAR_MAP              134
#define IDD_PROPERTIES                  135
#define IDD_PROPERTIES_ADVANCED_FEATURES 136
#define IDD_PROPERTIES_CSPROPS_FILE     137
#define IDD_PROPERTIES_JAVASCRIPT       138
#define IDD_PROPERTIES_JSON             139
#define IDD_PROPERTIES_MAPPING          140
#define IDD_PROPERTIES_MAPPING_TILE_PROVIDER 141
#define IDD_PROPERTIES_PARADATA         142
#define IDD_SELECT_APP                  143
#define IDD_SELECT_DOCS                 144
#define IDD_START                       145
#define IDD_SYMBOL_ANALYSIS             146
#define IDD_TROUBLESHOOTING             147
#define IDD_VERSION_SHIFTER             148
#define IDB_ABOUT_LOGO                  149
#define IDS_APPMODIFIED                 150
#define IDS_CANT_RENAME_DICT_IN_FORM    151
#define IDS_FILEOPEN                    152
#define IDS_INVLDAPPTYPE                153
#define IDS_OPENAPPFLD                  154
#define IDS_OVERWRITE_FILE              155
#define IDS_OVERWRITE_OPEN_FILE         156
#define IDS_SAVE_AS_SAVE_ERROR          157
#define IDC_ACCESS_TOKEN                1000
#define IDC_ACCESS_TOKEN_TEXT           1001
#define IDC_APPLICATION_FILENAME        1002
#define IDC_APPLIST                     1003
#define IDC_BASE_MAP                    1004
#define IDC_BUTTON_COMMON_STORE_DELETE  1005
#define IDC_BUTTON_COMMON_STORE_MODIFY  1006
#define IDC_CAPI_AUDIT_UNDEFINED_TEXT   1007
#define IDC_CAPI_INCLUDE_BLOCKS         1008
#define IDC_CAPI_INCLUDE_PROTECTED_FIELDS 1009
#define IDC_CAPI_INITIALIZE_FROM_DICTIONARY_LABEL 1010
#define IDC_CAPI_REMOVE_UNUSED_TEXT     1011
#define IDC_COMBO_COMMON_STORE_TYPE     1012
#define IDC_COORDINATE_DISPLAY_EXAMPLE  1013
#define IDC_CREATE_NEW                  1014
#define IDC_CSPROPS_FILENAME            1015
#define IDC_DECIMAL                     1016
#define IDC_DICTTREE                    1017
#define IDC_DMS                         1018
#define IDC_DOCS_LIST                   1019
#define IDC_EDIT_COMMON_STORE_ATTRIBUTE 1020
#define IDC_EDIT_COMMON_STORE_VALUE     1021
#define IDC_ELIGIBLE_VERSIONS           1022
#define IDC_ESRI                        1023
#define IDC_FILE                        1024
#define IDC_FILE_LIST                   1025
#define IDC_FILE_NEW                    1026
#define IDC_FILE_OPEN                   1027
#define IDC_FONT_CMB                    1028
#define IDC_FORMTREE                    1029
#define IDC_JAVASCRIPT_ABORT_MODULE_LOAD_ERROR 1030
#define IDC_JAVASCRIPT_ACTION_INVOKER_NAME 1031
#define IDC_JAVASCRIPT_BYTECODE_ONLY    1032
#define IDC_JAVASCRIPT_SCRIPTS_AND_BYTECODE 1033
#define IDC_JAVASCRIPT_SCRIPTS_ONLY     1034
#define IDC_JAVASCRIPT_USE_ACTION_INVOKER 1035
#define IDC_JSON_ARRAY                  1036
#define IDC_JSON_BINARY_CONTENT         1037
#define IDC_JSON_FORMAT                 1038
#define IDC_JSON_HASHMAP                1039
#define IDC_LIST_COMMON_STORE           1040
#define IDC_MAPBOX                      1041
#define IDC_MAPPING_ENGINE_DEFAULT      1042
#define IDC_MAPPING_ENGINE_LEAFLET      1043
#define IDC_MEASURETAB                  1044
#define IDC_NEW_FILE_CATEGORIES         1045
#define IDC_NEW_FILE_DESCRIPTION        1046
#define IDC_NEW_FILE_TYPES              1047
#define IDC_NEWGRID                     1048
#define IDC_OBJTREE                     1049
#define IDC_ONKEY_ALT                   1050
#define IDC_ONKEY_CHAR                  1051
#define IDC_ONKEY_CODE                  1052
#define IDC_ONKEY_CONTROL               1053
#define IDC_ONKEY_SHIFT                 1054
#define IDC_ONKEY_UNICODE_CHAR          1055
#define IDC_ONKEY_UNICODE_CODE          1056
#define IDC_OPEN_EXISTING               1057
#define IDC_ORDERTREE                   1058
#define IDC_PARADATA_DEVICE_STATE_MINUTES 1059
#define IDC_PARADATA_EVENTS             1060
#define IDC_PARADATA_EVENTS_ALL         1061
#define IDC_PARADATA_EVENTS_SOME        1062
#define IDC_PARADATA_EVENTS_NO          1063
#define IDC_PARADATA_GPS_LOCATION_MINUTES 1064
#define IDC_PARADATA_RECORD_COORDINATES 1065
#define IDC_PARADATA_RECORD_ENTERED_VALUES 1066
#define IDC_PARADATA_RECORD_INITIAL_PROPERTY_VALUES 1067
#define IDC_PARADATA_RECORD_ITERATOR_LOAD_CASES 1068
#define IDC_PASTE_FROM_CLIPBOARD        1069
#define IDC_PREVIEW_MAP                 1070
#define IDC_RADIO_COMMON_STORE_ADD      1071
#define IDC_RADIO_COMMON_STORE_MODIFY   1072
#define IDC_RESET_BTN                   1073
#define IDC_RESET_PROPERTIES            1074
#define IDC_SAVE_PROPERTIES_TO_APPLICATION 1075
#define IDC_SAVE_PROPERTIES_TO_CSPROPS  1076
#define IDC_SELECT_CSPROPS_FILE         1077
#define IDC_SELECT_OFFLINE_MAP          1078
#define IDC_SELECTALL                   1079
#define IDC_SYMBOL_ANALYSIS_CONTEXT     1080
#define IDC_SYMBOL_ANALYSIS_SYMBOLS_LABEL 1081
#define IDC_SYMBOL_ANALYSIS_TREE        1082
#define IDC_SYMBOL_ANALYSIS_USES        1083
#define IDC_SYMBOL_ANALYSIS_USES_LABEL  1084
#define IDC_TABLETREE                   1085
#define IDC_TILE_LAYERS                 1086
#define IDC_TROUBLESHOOTING_CSPROUSERS  1087
#define IDC_TROUBLESHOOTING_EMAIL       1088
#define IDC_TROUBLESHOOTING_PACK        1089
#define IDC_TROUBLESHOOTING_WEBSITE     1090
#define IDC_USE_COMPONENTS_INSTEAD_OF_NATIVE_VERSIONS 1091
#define IDC_USE_HTML_DIALOGS            1092
#define IDC_WORKING                     1093
#define IDC_ZOOMCMB                     1094
#define ID_ABOUT1                       40001
#define ID_CHANGE_TAB                   40002
#define ID_FILE_PROPERTIES              40003
#define ID_PREFERENCES_FONTS            40004
#define ID_STATUS_PANE_INDICATOR        40005
#define ID_TOOLS_VERSION_SHIFTER        40006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         40007
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           158
#endif
#endif
