#include <engine/StandardSystemIncludes.h>
#include <engine/StrictCompilerErrors.h>
#include <engine/x64_transition_strict.h>
#include "jsmin.h"
#include <zToolsO/Encoders.h>
#include <zToolsO/FileIO.h>
#include <zToolsO/Hash.h>
#include <zToolsO/Utf8.h>
#include <zJson/JsonSpecFile.h>
#include <zAction/ActionInvoker.h>
#include <zLogicO/GeneralizedFunction.h>


// to avoid frequently modifying FunctionTable.h, which causes a lot of files to be rebuilt,
// this flag controls whether to update function namespace table, which will be a rare occurrence
constexpr bool UpdateFunctionTableHeaderFile = false;


constexpr const char* ActionInvokerBaseNamespace = "CS";

constexpr std::string_view AutogeneratedStart_sv = "// --- CS_AUTOGENERATED_START";
constexpr std::string_view AutogeneratedEnd_sv   = "// --- CS_AUTOGENERATED_END";

constexpr const char* TabSpacing1   = "    ";
constexpr const char* TabSpacing2   = "        ";
constexpr const char* TabSpacing3   = "            ";
constexpr const char* LineSeparator = "// --------------------------------------------------------------------------";

constexpr std::string_view HashSalt_sv = "CS";
using HashType                         = unsigned short;
constexpr size_t HashLength            = sizeof(HashType);
constexpr size_t HashIterations        = 1024;


struct ActionInfo : public GF::Function
{
    const int hash;

    ActionInfo(const GF::Function& action_definition);

    std::string GetNamespaceAndName(char separator) const;
    std::string GetActionEnumClassId(bool name_only) const;
    std::string GetFunctionNamespaceEnumClassId(char separator) const;
    std::string GetHelpFilename() const;
    std::string GetActionInvokerMethodName() const;

private:
    int CalculateHash() const;
};


std::string CreateActionEnumText(const std::vector<ActionInfo>& action_infos);

std::string ConstructParameterText(const std::vector<GF::Parameter>& parameters);

std::string CreateFunctionTableText(const std::vector<ActionInfo>& action_infos);
std::string CreateJsonFunctionDefinitionsText(const std::vector<ActionInfo>& action_infos);

std::string CreateFunctionNamespaceEnumText(const std::vector<ActionInfo>& action_infos);

std::string CreateFunctionNamespaceDetailsText(const std::vector<ActionInfo>& action_infos);

std::string CreateFunctionDeclarationsText(const std::vector<ActionInfo>& action_infos);

std::string CreateFunctionMappingText(const std::vector<ActionInfo>& action_infos);

void CreateActionInvokerJavaScript(const std::vector<ActionInfo>& action_infos, const std::string& template_file_path, std::initializer_list<std::string> output_file_paths);

void ReplaceAutogeneratedRegion(const std::string& file_path, std::initializer_list<std::string> replacement_texts);
void ReplaceAutogeneratedRegion(std::string& file_text, std::string replacement_text, std::string_view autogenerated_start_text_sv, std::string_view autogenerated_end_text_sv);


int wmain(const int argc, const wchar_t* const argv[])
{
    try
    {
        if( argc < 2 )
            throw CSProException("Specify the location of the CSPro code directory.");

        const std::string code_directory = MakeFullPath(GetWorkingDirectory(), TC::ToUtf8(argv[1]));
        const std::string zAction_directory = Path::Combine(code_directory, "zAction");
        const std::string zLogicO_directory = Path::Combine(code_directory, "zLogicO");
        const std::string html_directory_windows = Path::Combine(code_directory, "html");
        const std::string html_directory_android = Path::Combine(code_directory, R"!(CSEntryDroid\app\src\main\assets\html)!");
        const std::string definitions_file_path = Path::Combine(zAction_directory, "action-definitions.json");

        // read the definitions...
        std::vector<GF::Function> action_definitions =
            [&]()
            {
                const std::unique_ptr<JsonSpecFile::Reader> json_reader = JsonSpecFile::CreateReader(definitions_file_path);
                return json_reader->GetArray().GetVector<GF::Function>();
            }();

        // ...sort by action namespace and name
        std::sort(action_definitions.begin(), action_definitions.end(),
            [&](const GF::Function& gf1, const GF::Function& gf2)
            {
                const int namespace_comparison = SO::CompareNoCase(gf1.namespace_name, gf2.namespace_name);
                return ( namespace_comparison != 0 ) ? ( namespace_comparison < 0 ) :
                                                       ( SO::CompareNoCase(gf1.name, gf2.name) < 0 );
            });

        // ...and resave the actions
        {
            const std::unique_ptr<JsonStringWriter> json_writer = Json::CreateStringWriter(JsonFormattingOptions::PrettySpacing);
            json_writer->Write(action_definitions);

            std::string actions_json = json_writer->ReleaseString();
            ASSERT(actions_json.back() == ']');
            actions_json.push_back('\n');
            SO::ConvertTabsToSpacesAndTrimRightEachLine(actions_json);

            FileIO::WriteText(definitions_file_path, actions_json, false);
        }


        // create the ActionInfo object for each action, which will create the action hashes
        std::vector<ActionInfo> action_infos;

        for( const GF::Function& action_definition : action_definitions )
            action_infos.emplace_back(action_definition);

        // write the ActionInvoker::Action enum class with associated hash values to zLogicO/ActionInvoker.h
        ReplaceAutogeneratedRegion(Path::Combine(zLogicO_directory, "ActionInvoker.h"), { CreateActionEnumText(action_infos) });

        // write the function table and definitions to zLogicO/ActionInvoker.cpp
        ReplaceAutogeneratedRegion(Path::Combine(zLogicO_directory, "ActionInvoker.cpp"), { CreateFunctionTableText(action_infos),
                                                                                            CreateJsonFunctionDefinitionsText(action_infos) });

        // write the FunctionNamespace enum class to zLogicO/FunctionTable.h
        if( UpdateFunctionTableHeaderFile )
            ReplaceAutogeneratedRegion(Path::Combine(zLogicO_directory, "FunctionTable.h"), { CreateFunctionNamespaceEnumText(action_infos) });

        // write the FunctionNamespace details to zLogicO/FunctionTable.cpp
        ReplaceAutogeneratedRegion(Path::Combine(zLogicO_directory, "FunctionTable.cpp"), { CreateFunctionNamespaceDetailsText(action_infos) });

        // write the function declarations to zAction/ActionInvoker.h
        ReplaceAutogeneratedRegion(Path::Combine(zAction_directory, "ActionInvoker.h"), { CreateFunctionDeclarationsText(action_infos) });

        // write the functions to the function mapping in zAction/ActionFunctionMapping.cpp
        ReplaceAutogeneratedRegion(Path::Combine(zAction_directory, "ActionFunctionMapping.cpp"), { CreateFunctionMappingText(action_infos) });

        // create the JavaScript files for the Windows and Android environments
        CreateActionInvokerJavaScript(action_infos, Path::Combine(zAction_directory, "action-invoker-template.js"),
            {
                Path::Combine(html_directory_windows, "action-invoker.js"),
                Path::Combine(html_directory_android, "action-invoker.js"),
            });
    }

    catch( const CSProException& exception )
    {
        MessageBoxW(nullptr, TC::ToWide(exception.what()).c_str(), L"Action Invoker Definition Updater", MB_OK | MB_ICONEXCLAMATION);
    }
}



// --------------------------------------------------------------------------
// ActionInfo
// --------------------------------------------------------------------------

ActionInfo::ActionInfo(const GF::Function& action_definition)
    :   GF::Function(action_definition),
        hash(CalculateHash())
{
}


int ActionInfo::CalculateHash() const
{
    const std::string action_name = GetNamespaceAndName('.');

    const std::vector<std::byte> hash_data = Hash::Hash(reinterpret_cast<const std::byte*>(action_name.data()), action_name.length(),
                                                        reinterpret_cast<const std::byte*>(HashSalt_sv.data()), HashSalt_sv.length(),
                                                        HashLength, HashIterations);
    ASSERT(hash_data.size() == sizeof(HashType));
    static_assert(sizeof(HashType) < sizeof(int));

    const int calculated_hash = *reinterpret_cast<const HashType*>(hash_data.data());
    ASSERT(calculated_hash >= 0);

    return calculated_hash;
}


std::string ActionInfo::GetNamespaceAndName(const char separator) const
{
    if( namespace_name.empty() )
        return name;

    return namespace_name + separator + name;
}


std::string ActionInfo::GetActionEnumClassId(const bool name_only) const
{
    std::string id = GetActionInvokerMethodName();

    if( name_only )
        return id;

    return "ActionInvoker::Action::" + id;
}


std::string ActionInfo::GetFunctionNamespaceEnumClassId(const char separator) const
{
    if( namespace_name.empty() )
        return ActionInvokerBaseNamespace;

    return std::string(ActionInvokerBaseNamespace) + separator + namespace_name;
}


std::string ActionInfo::GetHelpFilename() const
{
    // modify some mappings:
    //     - UI.closeDialog -> UI.close
    //     - Logic.updateSymbolValue -> Logic.setSymbolValue
    const char* const name_to_use =
        ( namespace_name == "UI" && name == "closeDialog" )          ? "close" :
        ( namespace_name == "Logic" && name == "updateSymbolValue" ) ? "setSymbolValue" :
                                                                       name.c_str();

    return FormatText("%s_%s.html", GetFunctionNamespaceEnumClassId('_').c_str(), name_to_use);
}


std::string ActionInfo::GetActionInvokerMethodName() const
{
    return GetNamespaceAndName('_');
}



// --------------------------------------------------------------------------
// other functions
// --------------------------------------------------------------------------

std::string CreateActionEnumText(const std::vector<ActionInfo>& action_infos)
{
    struct EnumNameAndHashCode
    {
        std::string enum_name;
        std::string hash_code;
    };

    std::vector<EnumNameAndHashCode> enum_name_and_hash_codes;
    size_t longest_enum_name = 0;
    size_t longest_hash_code = 0;
    std::set<int> already_calculated_hashes;

    for( const ActionInfo& action_info : action_infos )
    {
        const EnumNameAndHashCode& enum_name_and_hash_code = enum_name_and_hash_codes.emplace_back(
            EnumNameAndHashCode { action_info.GetActionEnumClassId(true), IntToString(action_info.hash) });

        longest_enum_name = std::max(longest_enum_name, enum_name_and_hash_code.enum_name.length());
        longest_hash_code = std::max(longest_hash_code, enum_name_and_hash_code.hash_code.length());

        // make sure each hash is unique
        if( already_calculated_hashes.find(action_info.hash) != already_calculated_hashes.cend() )
            throw CSProException("The hash code %d is duplicated", action_info.hash);

        already_calculated_hashes.insert(action_info.hash);
    }

    // generate the enum class
    std::string action_enum_text;

    for( const EnumNameAndHashCode& enum_name_and_hash_code : enum_name_and_hash_codes )
    {
        const size_t enum_name_spacing = longest_enum_name - enum_name_and_hash_code.enum_name.length();
        const size_t hash_code_spacing = longest_hash_code - enum_name_and_hash_code.hash_code.length();

        action_enum_text.append(FormatText("%s%s%*s = %*s%s,\n", TabSpacing2,
                                           enum_name_and_hash_code.enum_name.c_str(), static_cast<int>(enum_name_spacing), "",
                                           static_cast<int>(hash_code_spacing), "", enum_name_and_hash_code.hash_code.c_str()));
    }

    return action_enum_text;
}


std::string ConstructParameterText(const std::vector<GF::Parameter>& parameters)
{
    std::string parameter_text;
    std::vector<const GF::Parameter*> not_required_parameters;

    auto get_parameter_text = [&](const GF::Parameter& parameter)
    {
        ASSERT(!parameter.variable.types.empty());

        std::string parameter_text = FormatText("%s := %s", parameter.variable.name.c_str(), ToString(parameter.variable.types.front()));

        for( size_t i = 1; i < parameter.variable.types.size(); ++i )
            parameter_text.append(" | ").append(ToString(parameter.variable.types[i]));

        return parameter_text;
    };

    // add required parameters
    for( const GF::Parameter& parameter : parameters )
    {
        if( parameter.required )
        {
            SO::AppendWithSeparator(parameter_text, get_parameter_text(parameter), ", ");
        }

        else
        {
            not_required_parameters.emplace_back(&parameter);
        }
    }

    // add not-required parameters
    if( !not_required_parameters.empty() )
    {
        const auto& not_required_parameters_cend = not_required_parameters.cend();

        for( auto not_required_parameters_itr = not_required_parameters.cbegin();
             not_required_parameters_itr != not_required_parameters_cend;
             ++not_required_parameters_itr )
        {
            parameter_text.append(( not_required_parameters_itr != not_required_parameters.cbegin() ) ? ", " :
                                  ( parameter_text.empty() )                                          ? "[" :
                                                                                                        "[, ");
            parameter_text.append(get_parameter_text(*(*not_required_parameters_itr)));
        }

        parameter_text.push_back(']');
    }

    return parameter_text;
}


std::string CreateFunctionTableText(const std::vector<ActionInfo>& action_infos)
{
    std::string function_table_text;
    std::optional<std::string> previous_namespace_name;

    for( const ActionInfo& action_info : action_infos )
    {
        if( previous_namespace_name != action_info.namespace_name )
        {
            if( previous_namespace_name.has_value() )
                function_table_text.append("\n\n");

            function_table_text.append(FormatText("%s%s\n%s// %s functions\n%s%s\n",
                                                  TabSpacing2, LineSeparator,
                                                  TabSpacing2, action_info.GetFunctionNamespaceEnumClassId('.').c_str(),
                                                  TabSpacing2, LineSeparator));

            previous_namespace_name = action_info.namespace_name;
        }

        function_table_text.append(FormatText("%s{\n", TabSpacing2));
        function_table_text.append(FormatText("%s\"%s\",\n", TabSpacing3, action_info.name.c_str()));
        function_table_text.append(FormatText("%s\"%s.%s(%s)\",\n", TabSpacing3, ActionInvokerBaseNamespace, action_info.GetNamespaceAndName('.').c_str(), ConstructParameterText(action_info.parameters).c_str()));
        function_table_text.append(FormatText("%s\"%s\",\n", TabSpacing3, action_info.GetHelpFilename().c_str()));
        function_table_text.append(FormatText("%sFunctionCode::CSFN_ACTIONINVOKER_CODE,\n", TabSpacing3));
        function_table_text.append(FormatText("%sFunctionNamespace::%s,\n", TabSpacing3, action_info.GetFunctionNamespaceEnumClassId('_').c_str()));
        function_table_text.append(FormatText("%sDataType::String,\n", TabSpacing3));
        function_table_text.append(FormatText("%sFunctionCompilationType::CS,\n", TabSpacing3));
        function_table_text.append(FormatText("%sstatic_cast<int>(%s),\n", TabSpacing3, action_info.GetActionEnumClassId(false).c_str()));
        function_table_text.append(FormatText("%s},\n", TabSpacing2));
    }

    return function_table_text;
}


std::string CreateJsonFunctionDefinitionsText(const std::vector<ActionInfo>& action_infos)
{
    std::vector<std::string> enum_names;
    size_t longest_enum_name = 0;

    for( const ActionInfo& action_info : action_infos )
    {
        const std::string& enum_name = enum_names.emplace_back(action_info.GetActionEnumClassId(false));
        longest_enum_name = std::max(longest_enum_name, enum_name.length());
    }

    std::string json_function_definitions_text;
    auto enum_names_itr = enum_names.cbegin();

    for( const ActionInfo& action_info : action_infos )
    {
        std::unique_ptr<JsonStringWriter> json_writer = Json::CreateStringWriter(JsonFormattingOptions::Compact);
        json_writer->Write(action_info);

        const size_t enum_name_spacing = longest_enum_name - enum_names_itr->length();

        json_function_definitions_text.append(FormatText("%s{ %s,%*s \"%s\" },\n", TabSpacing2,
                                                         enum_names_itr->c_str(),
                                                         static_cast<int>(enum_name_spacing), "",
                                                         Encoders::ToEscapedString(json_writer->GetString(), false).c_str()));

        ++enum_names_itr;
    }

    return json_function_definitions_text;
}


std::string CreateFunctionNamespaceEnumText(const std::vector<ActionInfo>& action_infos)
{
    std::string function_namespace_enum_text;
    std::optional<std::string> previous_enum_name;

    for( const ActionInfo& action_info : action_infos )
    {
        std::string enum_name = action_info.GetFunctionNamespaceEnumClassId('_');

        if( previous_enum_name != enum_name )
        {
            function_namespace_enum_text.append(FormatText("%s%s,\n", TabSpacing2, enum_name.c_str()));
            previous_enum_name = std::move(enum_name);
        }
    }

    return function_namespace_enum_text;
}


std::string CreateFunctionNamespaceDetailsText(const std::vector<ActionInfo>& action_infos)
{
    std::string function_namespace_details_text;
    std::optional<std::string> previous_enum_name;
    constexpr size_t longest_namespace_name = 11;
    constexpr size_t longest_enum_name = 14;
    constexpr size_t longest_parent_function_namespace = 22;
    constexpr size_t longest_help_filename = 19;

    for( const ActionInfo& action_info : action_infos )
    {
        const std::string namespace_name = action_info.namespace_name.empty() ? ActionInvokerBaseNamespace :
                                                                                action_info.namespace_name;
        const std::string enum_name = action_info.GetFunctionNamespaceEnumClassId('.');

        if( previous_enum_name != enum_name )
        {
            const std::string parent_function_namespace = action_info.namespace_name.empty() ? "std::nullopt" :
                                                                                               SO::Concatenate("FunctionNamespace::", ActionInvokerBaseNamespace);

            const std::string help_filename = action_info.namespace_name.empty() ? "action_invoker.html" :
                                                                                   ( action_info.GetFunctionNamespaceEnumClassId('_') + ".html" );

            auto get_spacing_length = [&](const size_t longest_value, const std::string& text) -> int
            {
                if( longest_value < text.length() )
                    throw CSProException("Increase the spacing of FunctionNamespaces");

                return static_cast<int>(longest_value - text.length());
            };

            function_namespace_details_text.append(FormatText("%s{ \"%s\",%*s FunctionNamespace::%s,%*s %s,%*s \"%s\"%*s },\n", TabSpacing2,
                                                              namespace_name.c_str(), get_spacing_length(longest_namespace_name, namespace_name), "",
                                                              action_info.GetFunctionNamespaceEnumClassId('_').c_str(), get_spacing_length(longest_enum_name, enum_name), "",
                                                              parent_function_namespace.c_str(), get_spacing_length(longest_parent_function_namespace, parent_function_namespace), "",
                                                              help_filename.c_str(), get_spacing_length(longest_help_filename, help_filename), ""));

            previous_enum_name = enum_name;
        }
    }

    return function_namespace_details_text;
}


std::string CreateFunctionDeclarationsText(const std::vector<ActionInfo>& action_infos)
{
    std::string function_declarations_text;

    for( const ActionInfo& action_info : action_infos )
        function_declarations_text.append(FormatText("%sResult %s(const JsonNode& json_node, Caller& caller);\n", TabSpacing1, action_info.GetActionInvokerMethodName().c_str()));

    return function_declarations_text;
}


std::string CreateFunctionMappingText(const std::vector<ActionInfo>& action_infos)
{
    std::string function_mapping_text;
    std::vector<std::string> method_names;
    size_t longest_method_name = 0;

    for( const ActionInfo& action_info : action_infos )
    {
        const std::string& method_name = method_names.emplace_back(action_info.GetActionInvokerMethodName());
        longest_method_name = std::max(longest_method_name, method_name.length());
    }

    for( const std::string& method_name : method_names )
    {
        const size_t method_name_spacing = longest_method_name - method_name.length();

        function_mapping_text.append(FormatText("%s{ Action::%s,%*s &Runtime::%s%*s },\n", TabSpacing1,
                                                method_name.c_str(), static_cast<int>(method_name_spacing), "",
                                                method_name.c_str(), static_cast<int>(method_name_spacing), ""));
    }

    return function_mapping_text;
}


void CreateActionInvokerJavaScript(const std::vector<ActionInfo>& action_infos, const std::string& template_file_path, const std::initializer_list<std::string> output_file_paths)
{
    std::string js_text = FileIO::ReadText(template_file_path);
    SO::MakeNewlineLF(js_text);

    std::string functions_text = "\n";

    std::optional<std::string> previous_namespace_name;
    std::optional<size_t> in_namespace_action_index;

    auto end_namespace_if_necessary = [&]()
    {
        if( in_namespace_action_index.has_value() )
        {
            ASSERT(*in_namespace_action_index > 0);
            functions_text.append("\n};\n");
            in_namespace_action_index.reset();
        }
    };

    for( const ActionInfo& action_info : action_infos )
    {
        if( previous_namespace_name != action_info.namespace_name )
        {
            end_namespace_if_necessary();

            if( !action_info.namespace_name.empty() )
            {
                functions_text.append(FormatText("\n%s = {\n", action_info.namespace_name.c_str()));
                in_namespace_action_index = 0;
            }

            previous_namespace_name = action_info.namespace_name;
        }

        auto get_function_body = [&](const bool async)
        {
            return FormatText("{return CSProActionInvoker.$Impl.run%s(this,%d,args);}",
                              async ? std::string(ActionInvoker::AsyncActionSuffix_sv).c_str() : "",
                              action_info.hash);
        };

        if( in_namespace_action_index.has_value() )
        {
            functions_text.append(FormatText("%s  %s: (args)=>%s,\n",
                                             ( *in_namespace_action_index == 0 ) ? "" : ",\n",
                                             action_info.name.c_str(),
                                             get_function_body(false).c_str()));

            functions_text.append(FormatText("  %s%s: (args)=>%s",
                                             action_info.name.c_str(), std::string(ActionInvoker::AsyncActionSuffix_sv).c_str(),
                                             get_function_body(true).c_str()));

            ++(*in_namespace_action_index);
        }

        else
        {
            functions_text.append(FormatText("%s(args) %s\n",
                                             action_info.name.c_str(),
                                             get_function_body(false).c_str()));

            functions_text.append(FormatText("%s%s(args) %s\n",
                                             action_info.name.c_str(), std::string(ActionInvoker::AsyncActionSuffix_sv).c_str(),
                                             get_function_body(true).c_str()));
        }
    }

    end_namespace_if_necessary();


    // insert a dummy function in the area where the functions will go post-minification
    constexpr std::string_view DummyFunctionText_sv = "cspro-replace(){};";

    ReplaceAutogeneratedRegion(js_text, std::string(DummyFunctionText_sv), AutogeneratedStart_sv, AutogeneratedEnd_sv);

    // minify the code
    std::string js_minified_text = CSPro::jsmin(js_text);
    SO::MakeTrim(js_minified_text);

    // move the end brace of the class to a new line
    ASSERT(js_minified_text.back() == '}');
    js_minified_text.insert(js_minified_text.end() - 1, '\n');

    SO::MakeTrim(js_minified_text);

    // replace the dummy function with our functions text
    SO::Replace(js_minified_text, DummyFunctionText_sv, functions_text);

    js_minified_text.push_back('\n');

    for( const std::string& output_file_path : output_file_paths )
        FileIO::WriteText(output_file_path, js_minified_text, false);
}


void ReplaceAutogeneratedRegion(const std::string& file_path, const std::initializer_list<std::string> replacement_texts)
{
    std::string file_text = FileIO::ReadText(file_path);
    SO::MakeNewlineLF(file_text);

    size_t block_counter = 0;

    for( const std::string& replacement_text : replacement_texts )
    {
        std::string autogenerated_start_text(AutogeneratedStart_sv);
        std::string autogenerated_end_text(AutogeneratedEnd_sv);

        if( replacement_texts.size() > 1 )
        {
            std::string block_suffix = FormatText("_%d", ++block_counter);
            autogenerated_start_text.append(block_suffix);
            autogenerated_end_text.append(block_suffix);
        }

        ReplaceAutogeneratedRegion(file_text, replacement_text, autogenerated_start_text, autogenerated_end_text);
    }

    SO::MakeNewlineCRLF(file_text);
    FileIO::WriteText(file_path, file_text, true);
}


void ReplaceAutogeneratedRegion(std::string& file_text, std::string replacement_text, const std::string_view autogenerated_start_text_sv, const std::string_view autogenerated_end_text_sv)
{
    const size_t start_pos = file_text.find(autogenerated_start_text_sv);

    if( start_pos == std::string::npos )
        throw CSProException("The autogenerated start cannot be found: " + std::string(autogenerated_start_text_sv));

    const size_t end_pos = file_text.find(autogenerated_end_text_sv, start_pos + autogenerated_start_text_sv.length());

    if( end_pos == std::string::npos )
        throw CSProException("The autogenerated end cannot be found: " + std::string(autogenerated_end_text_sv));

    // move the start position to the next line and the end position to the previous line
    auto start_itr = file_text.begin() + start_pos;
    auto end_itr = file_text.begin() + end_pos;

    while( start_itr < end_itr && *start_itr != '\n' )
        ++start_itr;

    while( end_itr > start_itr && *end_itr != '\n' )
        --end_itr;

    // add newlines to space out the content from the autogenerated markers
    replacement_text.insert(0, 2, '\n');

    if( replacement_text.back() != '\n' )
        replacement_text.push_back('\n');

    // replace the text
    file_text.replace(start_itr, end_itr, replacement_text);
}
