project(zUtilO)

add_library(${PROJECT_NAME}
    BasicLogger.cpp
    BinaryContentCacher.cpp
    BinaryDataAccessor.cpp
    BinaryDataMetadata.cpp
    CommonStore.cpp
    ConnectionString.cpp
    CredentialStore.cpp
    CSProExecutables.cpp
    CustomUri.cpp
    DataTypes.cpp
    ExecutionStack.cpp
    ExpansiveList.cpp
    ExpansiveMap.cpp
    FileExtensions.cpp
    ImsaStr.cpp
    Interapp.cpp
    MediaStore.cpp
    MimeType.cpp
    MimeTypeMap.cpp
    NameShortener.cpp
    PathHelpers.cpp
    PortableColor.cpp
    PortableFileSystem.cpp
    PortableFont.cpp
    ProcessSummary.cpp
    PropertyString.cpp
    Randomizer.cpp
    SettingsDb.cpp
    SimpleDbMap.cpp
    SpecFile.cpp
    SpecialDirectoryLister.cpp
    SQLiteSchema.cpp
    SqlLogicFunctions.cpp
    StdioFileUnicode.cpp
    SyncConnectionString.cpp
    TemporaryFile.cpp
    TextSource.cpp
    TextSourceEditable.cpp
    TextSourceExternal.cpp
    TransactionManager.cpp
    Versioning.cpp
    Viewers.cpp
    VirtualDirectoryLister.cpp
)
