project(zEngineO)

include_directories(${PROJECT_NAME} PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}
    ${EXTERNAL_DIRECTORY}/geometry.hpp/include
    ${EXTERNAL_DIRECTORY}/variant/include
)

add_library(${PROJECT_NAME}
    Audio.cpp
    Array.cpp
    BinarySymbol.cpp
    BinarySymbolData.cpp
    Block.cpp
    Document.cpp
    EngineCase.cpp
    EngineData.cpp
    EngineDataRepository.cpp
    EngineDictionary.cpp
    EngineItem.cpp
    EngineRecord.cpp
    EngineValue.cpp
    File.cpp
    Flow.cpp
    Geometry.cpp
    HashMap.cpp
    Image.cpp
    Imputation.cpp
    JavaScriptProcessor.cpp
    List.cpp
    LogicByteCode.cpp
    LoopStack.cpp
    Map.cpp
    NamedFrequency.cpp
    ParameterManager.cpp
    PenReaderApplicationLoader.cpp
    PersistentVariableProcessor.cpp
    Pff.cpp
    PffExecutor.cpp
    PreinitializedVariable.cpp
    ProcType.cpp
    Report.cpp
    ResponseProcessor.cpp
    RunnableSymbol.cpp
    RuntimeEvent.cpp
    SaveArrayFile.cpp
    StringWriter.cpp
    SymbolCalculator.cpp
    SystemApp.cpp
    UserFunction.cpp
    UserFunctionArgumentChecker.cpp
    UserFunctionArgumentEvaluator.cpp
    UserFunctionLocalSymbolsManager.cpp
    ValueSet.cpp
    Video.cpp
    WorkString.cpp
    WorkVariable.cpp

    Compiler/ActionInvokerCC.cpp
    Compiler/ArgumentSpecificationCompiler.cpp
    Compiler/ArrayCC.cpp
    Compiler/AudioCC.cpp
    Compiler/BarcodeCC.cpp
    Compiler/CaseCC.cpp
    Compiler/CompilerHelper.cpp
    Compiler/CompilersCC.cpp
    Compiler/ControlFlowCC.cpp
    Compiler/DataAccessCC.cpp
    Compiler/DictionaryCC.cpp
    Compiler/DocumentCC.cpp
    Compiler/EngineDictionaryCC.cpp
    Compiler/EnginePreprocessor.cpp
    Compiler/ExpressionsCC.cpp
    Compiler/FileCC.cpp
    Compiler/FreqCC.cpp
    Compiler/FunctionsGenericCC.cpp
    Compiler/FunctionsVariousCC.cpp
    Compiler/GeometryCC.cpp
    Compiler/GpsCC.cpp
    Compiler/HashMapCC.cpp
    Compiler/ImageCC.cpp
    Compiler/ImputeCC.cpp
    Compiler/ItemCC.cpp
    Compiler/JavaScriptCC.cpp
    Compiler/JsonCC.cpp
    Compiler/ListCC.cpp
    Compiler/LogicCompiler.cpp
    Compiler/MapCC.cpp
    Compiler/MathCC.cpp
    Compiler/MessagesCC.cpp
    Compiler/NextTokenCC.cpp
    Compiler/NodeCreationCC.cpp
    Compiler/OptionalNamedArgumentsCompiler.cpp
    Compiler/PathCC.cpp
    Compiler/PffCC.cpp
    Compiler/QueryCC.cpp
    Compiler/ReportCC.cpp
    Compiler/RoutingCC.cpp
    Compiler/StringsCC.cpp
    Compiler/StringWriterCC.cpp
    Compiler/SwitchCC.cpp
    Compiler/SymbolsCC.cpp
    Compiler/SyncCC.cpp
    Compiler/SystemAppCC.cpp
    Compiler/TextTemplateCC.cpp
    Compiler/TokenCC.cpp
    Compiler/TraceCC.cpp
    Compiler/UserbarCC.cpp
    Compiler/UserFunctionCC.cpp
    Compiler/UserInterfaceCC.cpp
    Compiler/ValueSetCC.cpp
    Compiler/VariableCC.cpp
    Compiler/VideoCC.cpp

    Interpreter/ActionInvokerRT.cpp
    Interpreter/ArrayRT.cpp
    Interpreter/AudioRT.cpp
    Interpreter/BarcodeRT.cpp
    Interpreter/BytecodeRT.cpp
    Interpreter/CompressionRT.cpp
    Interpreter/ControlFlowRT.cpp
    Interpreter/DateRT.cpp
    Interpreter/DocumentRT.cpp
    Interpreter/ExecutionRT.cpp
    Interpreter/GeometryRT.cpp
    Interpreter/HashMapRT.cpp
    Interpreter/ImageRT.cpp
    Interpreter/InstructionsRT.cpp
    Interpreter/ItemRT.cpp
    Interpreter/FileRT.cpp
    Interpreter/JavaScriptRT.cpp
    Interpreter/JsonRT.cpp
    Interpreter/ListRT.cpp
    Interpreter/LocalhostRT.cpp
    Interpreter/LogicInterpreter.cpp
    Interpreter/LogicRT.cpp
    Interpreter/MapRT.cpp
    Interpreter/MathRT.cpp
    Interpreter/MessagesRT.cpp
    Interpreter/MovementRT.cpp
    Interpreter/NetworkRT.cpp
    Interpreter/PathRT.cpp
    Interpreter/PffRT.cpp
    Interpreter/PropertiesRT.cpp
    Interpreter/QueryRT.cpp
    Interpreter/ReportRT.cpp
    Interpreter/RuntimeRT.cpp
    Interpreter/StringRT.cpp
    Interpreter/StringWriterRT.cpp
    Interpreter/SwitchRT.cpp
    Interpreter/SymbolRT.cpp
    Interpreter/SyncRT.cpp
    Interpreter/SystemAppRT.cpp
    Interpreter/SystemRT.cpp
    Interpreter/TextTemplateRT.cpp
    Interpreter/TraceRT.cpp
    Interpreter/UserbarRT.cpp
    Interpreter/UserFunctionRT.cpp
    Interpreter/UserInterfaceRT.cpp
    Interpreter/ValueSetRT.cpp
    Interpreter/VariableRT.cpp
    Interpreter/VideoRT.cpp
)

target_precompile_headers(${PROJECT_NAME} PRIVATE
    stdafx.h
)
